# Generated by Django 3.0.3 on 2020-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_auto_20200223_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
